@echo off
echo Compiling boot sector...
"../toolkit/nasm-2.15.05/nasm.exe" -f bin "src/boot/bootloader.asm" -o "bootloader.bin"
echo Compiling moloukhiya...
"../toolkit/nasm-2.15.05/nasm.exe" -f bin "src/kernel/moloukhiya.asm" -o "moloukhiya.bin"
echo Merging into floopy disk...
copy /b bootloader.bin+moloukhiya.bin os.flp >nul
echo Deleting excess files...
del bootloader.bin
del moloukhiya.bin
echo Done!
pause >nul
goto :eof
